#ifndef __REQUESTS_H_INCLUDED__
#define __REQUESTS_H_INCLUDED__


#define DUQX_ADC_READ_SINGLE		1
#define DUQX_ADC_READ_BUFFER		2
#define DUQX_ADC_PRESCALER_SET   	3
#define DUQX_ADC_ENABLED_SET		4
#define DUQX_ADC_RESOLUTION_SET 	5
#define DUQX_DAC_WRITE_SINGLE       6
#define DUQX_DIGITAL_CONFIGURE	    7
#define DUQX_DIGITAL_WRITE   	    8
#define DUQX_DIGITAL_READ    	    9

#endif
